version: '3.9'

services:
  django:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./appconfig-env
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    image: postgres:14.3-alpine3.16
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challenge
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  postgresql: 